vich_uploader:
    db_driver: orm

    mappings:
        room_image:
            uri_prefix: /images/rooms
            upload_destination: '%kernel.project_dir%/public/images/rooms'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
